version: '3.7'

services:

  produk-service:
    build: .
    image: produk-service:latest
    container_name: produk-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommerce_db:5432/ecommerce
      - SPRING_DATASOURCE_USERNAME=adehendini
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server/eureka
      - EUREKA_CLIENT_ENABLED=true
      - SERVER_PORT=80
      - S3_URL=http://localhost:9000
      - S3_ACCESSKEY=minio
      - S3_SECRETKEY=minio#123
    restart: always
    ports:
      - 10002:80
    networks:
      - hendi_network

networks:
  hendi_network:
    name: hendi_network