spring:
  application:
    name: foto-produk-service
  data:
    mongodb:
      database: ecommerce
      username: adehendini
      password: password
      port: 27017
      host: localhost
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

s3:
  url: http://localhost:9000
  accessKey: minio
  secretKey: minio#123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
