spring:
  application:
    name: discovery-server
server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
